version: '3.7'

services:

  react-frontend:
    container_name: todo-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:80'
    environment:
      - NODE_ENV=development